name: CI 🏗

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Lint & test code.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55.2"

      - run: go vet ./...

      - run: env CGO_ENABLED=0 go test -cover ./...

      - run: go test -race -cover ./...
