name: Release 🚀

on:
  release:
    types:
      - created

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          # linux/amd64
          go build
          tar -czvf go-varlink-cmd-${VERSION}-Linux-amd64.tar.zst go-varlink-cmd

          # linux/arm64
          env GOARCH=arm64 go build
          tar -czvf go-varlink-cmd-${VERSION}-Linux-arm64.tar.zst go-varlink-cmd
          rm go-varlink-cmd

          sha256sum go-varlink-cmd-*.tar.zst > sha256sums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: go-varlink-cmd
          path: |
            go-varlink-cmd-*.tar.zst
            sha256sums.txt

      - uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: |
            go-varlink-cmd-*.tar.zst
            sha256sums.txt
